auth:
  loginUrl: /admin/login

  jwt:
    secret: seed
    expiresIn: 1800s
  cookie:
    name: token

cookie:
  secret: seed

data_access:
  dialect: 'mysql'
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: '!QAZ2wsx'
  database: 'nesttest'

app:
  title: 标题
  description: 描述...
  apps: default,sample
