auth:
  loginUrl: /admin/login

  jwt:
    secret: seed
    expiresIn: 1800s
  cookie:
    name: token

cookie:
  secret: seed

data_access:
  dialect: 'mysql'
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: '!QAZ2wsx'
  database: 'nesttest'
  logging: false

app:
  title: 标题
  description: 描述...

  sitemap:
    - path: page1
      meta:
        title: page1 title
        icon: chart
      children:
        - path: page2
          meta:
            title: page2 title
            icon: chart
        - path: page3
          meta:
            hidden: true
        - path: page4
          meta:
            title: page4 title
            icon: chart
    - path: page5
      meta:
        title: page5 title
        icon: chart

  apps:
    default:
    sample:
