config:
  createdAt: false
  updatedAt: false

columns:
  id:
    type: INTEGER
    primaryKey: true
  name:
    type: STRING(50)
    allowNull: false
  remark:
    type: STRING
  num:
    type: INTEGER
